#!/bin/bash

THIS_SCRIPT=${BASH_SOURCE[0]}
THIS_DIRECTORY=$(cd $(dirname ${THIS_SCRIPT}) && pwd)

REPOSITORY="aaron8bit"
IMAGE_NAME="ubuntu18dev"
#IMAGE="${REPOSITORY}/${IMAGE_NAME}"
IMAGE="${IMAGE_NAME}"

IMAGE_TAG="latest"

exec docker run \
     -it \
     --init \
     --hostname=DevDocker \
     --rm=true \
     --net=host \
     -e TZ=`ls -la /etc/localtime | cut -d/ -f8-9` \
     --volume=/var/run/docker.sock:/var/run/docker.sock \
     --volume=${HOME}/.ssh:/home/aaron/.ssh \
     --volume=${HOME}/repos:/home/aaron/repos \
     --volume=${HOME}/docker:/home/aaron/docker \
     --volume=${HOME}/tmp:/home/aaron/tmp \
     --workdir=/home/aaron \
     ${IMAGE}:${IMAGE_TAG} \
     zsh 

