#!/bin/bash

THIS_SCRIPT=${BASH_SOURCE[0]}
THIS_DIRECTORY=$(cd $(dirname ${THIS_SCRIPT}) && pwd)

REPOSITORY="aaron8bit"
IMAGE_NAME="centos7dev"
IMAGE="${REPOSITORY}/${IMAGE_NAME}"

IMAGE_TAG="latest"

exec docker run \
     -it \
     --hostname=DevDocker \
     --rm=true \
     --net=host \
     --volume=/etc/localtime:/etc/localtime \
     --volume=${HOME}/.ssh:/home/aja/.ssh:ro \
     --volume=${HOME}/repos:/home/aja/repos \
     --workdir=/home/aja/repos \
     ${IMAGE}:${IMAGE_TAG} \
     zsh 

